-- Generated by nwg-displays on 2026-06-20 at 21:40:36. Do not edit manually.

hl.monitor({
    output = "desc:Xiaomi Corporation P27FBB-RGGL 5275600014925",
    mode = "1920x1080@165.0",
    position = "1920x0",
    scale = 1.0
})
hl.monitor({
    output = "desc:AU Optronics 0x5895",
    mode = "1920x1080@165.01",
    position = "0x0",
    scale = 1.0
})
